# https://taskfile.dev

version: '3'

vars:
  BATCH: emacs -Q --batch -L . -L misc -L test

tasks:
   
  build:
    sources:
      - './*.el'
      - './misc/*.el'
      - exclude: './misc/simple-pomodoro-notification.el'

    generates:
      - './*.elc'
      - './misc/*.elc'
    cmds:
      - for: sources
        cmd: '{{ .BATCH }} -f batch-byte-compile {{ .ITEM }}'

  test:
    deps: [build]
    cmds:
      - '{{ .BATCH }} -l test/simple-pomodoro-tests.el -l ert --eval "(ert-run-tests-batch-and-exit)"'
  clean:
    cmds:
      - find . -type f -name "*.elc" | xargs rm
